Traceback (most recent call last):
  File "C:\Users\apnat\Desktop\Automate the boring Stuff\raiseAndAssert.py", line 3, in <module>
    raise Exception('This is an error message.')
Exception: This is an error message.
